version: '3.4'

services:
  auditapp.extranet:
    image: ${DOCKER_REGISTRY-}auditappextranet
    build:
      context: .
      dockerfile: AuditApp.Api/Dockerfile

  client: 
    image: client
    build: 
      context: ./AuditApp.Api/Frontend
      dockerfile: Dockerfile

  proxy: 
    image: nginx:mainline

